image: Visual Studio 2017
init:
    - git config --global core.autocrlf input

clone_folder: c:\projects\test_cross_platform
shallow_clone: true

matrix:
    fast_finish: false

platform:
    - x64

configuration:
    - Debug
    - Release

environment:
    matrix:
        - TOOLCHAIN: msvc15

install:
    - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"