image: Visual Studio 2015
init:
    - git config --global core.autocrlf input

clone_folder: c:\projects\test_cross_platform
shallow_clone: true

matrix:
    fast_finish: false

platform:
    - x64

configuration:
    - Debug
    - Release

environment:
    matrix:
        - TOOLCHAIN: msvc15

install:
     - call ci\appveyor\set-env.bat %TOOLCHAIN% %PLATFORM%