dist: trusty
sudo: required

language: cpp
os: linux
compiler: gcc

env:
    - TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
    - TARGET_CPU=x86 BUILD_CONFIGURATION=Release

before_script:
    - sudo apt-get update -qq
    - sudo apt-get install libboost-all-dev

script:
    - mkdir build
    - cd build
    - cmake ..
    - make
