sudo: required
os: linux
dist: trusty
language: cpp
compiler: gcc
env:
    - TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
    - TARGET_CPU=x86 BUILD_CONFIGURATION=Release
before_script:
    - sudo apt-get update -qq
    - sudo apt-get install libboost-all-dev
script:
    - make
deploy:
    provider: releases
    api_key:
      secure: z5dzyCE9psEzvMluYn84q34sLa32FNoe2HkTkn4kfXDp+ejfYyq8UGjIQlDLW2STRKYKJFdejkCejwEB6+LLsBa2gcpNef/ga9PCnXoH4pVQpKIGdqrl5oKLfLd0v8LX7vKefSCM0AaEiOKc0XF6ailmMmJyz1yVLsxhe7JTnWrEjg+ol1PmnLfreahKgDcXmvPhS8DbvQNkTNficM/HCjbwTgfc7Gc+KhnlsozjcGW9YCLF+OhuuHQ/eaNm4ooayUj1aFIjZGoez/GVGHIP+pEiFFxi+IQow21N/yAvh38DQXnVvJKR3Sor8qtcXS8vkPio5fVx0LKb9CCCH//0mCqtOQkKlWlMVm9dI90Uw9m6R/dFQzo6WZPLmKIV5CZZN6OXZcuAqSU4LtFPdOKcSgM71ZHe3OOtOIF/OGH8B1UsjfRpyDsIyaIqL/vX91WePW3lL2fVLLExfsqF3bd757hKcyK6KdNdrv7PVT6qFsR/toDOCuIPbM1q42bIJ4ZjE+5z/9UG3WQWVjleN6wSSkAXvlHMt/SeBtH4rt0peEeSOzExr//hQbPq++Wfte2Sm6HuNLKIdV1rkoU/0pLf/kXwfLqxAf0YcIf7xxCBzTr3YT2S5XYA3qPSU7OMEjUtBl6nHnYSpR3RpFPfQysJ6i07toubq+Z28eDnURlqLdI=
    file: out/*
    on:
        repo: TheDeepestSpace/test_cross_platform
