dist: trusty
sudo: required

language: cpp
os: linux
compiler: gcc

env:
    - TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
    - TARGET_CPU=x86 BUILD_CONFIGURATION=Release

matrix:
    include:
        - env: 

install:
    - source ci/travis/install-$TRAVIS_OS_NAME$.sh